### ISSUE TITLE
cd $DAVSS_ROOT/lib/model/resample2d_package    python setup.py build  过程中的一系列报错

### ISSUE THREAD

**Issue by zhenzhen11414** [jfzhuang/DAVSS#3]
LINK : fatal error LNK1181: 无法打开输入文件“C:\video semantic segmentation\DAVSS-master\lib\model\resample2d_package\build\temp.win-amd64-3.7\Release\resample2d_cuda.obj”
error: command 'D:\\exe\\visual studio\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by jfzhuang** [comment]
Thanks for paying attention to the project. The project is not tested on Windows. Maybe you can try on the Linux.
